-- ─────────────────────────────────────────────────────────────────────────
-- 004_demo_organizations — INTENTIONALLY EMPTY (demo seed removed 2026-07).
--
-- This migration previously seeded demo users / organizations / a demo
-- system_admin (admin@/manager@/seller@/buyer@/ryan@ryanweiss.net, the
-- "rw3iss Marketplace" org, etc.). Those are NOT wanted in any deployment
-- (see 024_remove_demo_seed_data), so the seed is removed at the source.
-- Kept as a no-op (not deleted) to preserve the applied-migration history.
-- Roles/permissions live in 002_seed_data; real users self-register.
-- ─────────────────────────────────────────────────────────────────────────
SELECT 1;
